/**
 * BPS
 * Bubble Point System API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreditJournal from '../model/CreditJournal';
import Customer from '../model/Customer';
import Device from '../model/Device';
import DeviceInfo from '../model/DeviceInfo';
import Location from '../model/Location';
import ModuleProgramm200Response from '../model/ModuleProgramm200Response';
import Payment from '../model/Payment';
import PaymentRequest from '../model/PaymentRequest';
import PriceLine from '../model/PriceLine';
import Status from '../model/Status';
import TopupCreditRequest from '../model/TopupCreditRequest';
import UpdateCustomerRequest from '../model/UpdateCustomerRequest';
import UpdateModuleBinary404Response from '../model/UpdateModuleBinary404Response';

/**
* Default service.
* @module api/DefaultApi
* @version 0.1.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the allowStart operation.
     * @callback module:api/DefaultApi~allowStartCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Allows the start of a washer or dryer
     * @param {String} name The name of the device
     * @param {Number} value value / ms or count
     * @param {module:api/DefaultApi~allowStartCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Status}
     */
    allowStart(name, value, callback) {
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling allowStart");
      }
      // verify the required parameter 'value' is set
      if (value === undefined || value === null) {
        throw new Error("Missing the required parameter 'value' when calling allowStart");
      }

      let pathParams = {
      };
      let queryParams = {
        'name': name,
        'value': value
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Status;
      return this.apiClient.callApi(
        '/allowstart', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteDevice operation.
     * @callback module:api/DefaultApi~deleteDeviceCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a device
     * @param {String} location The shop location ID
     * @param {String} typ The type of the device
     * @param {Number} nr The number of the device
     * @param {module:api/DefaultApi~deleteDeviceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Status}
     */
    deleteDevice(location, typ, nr, callback) {
      let postBody = null;
      // verify the required parameter 'location' is set
      if (location === undefined || location === null) {
        throw new Error("Missing the required parameter 'location' when calling deleteDevice");
      }
      // verify the required parameter 'typ' is set
      if (typ === undefined || typ === null) {
        throw new Error("Missing the required parameter 'typ' when calling deleteDevice");
      }
      // verify the required parameter 'nr' is set
      if (nr === undefined || nr === null) {
        throw new Error("Missing the required parameter 'nr' when calling deleteDevice");
      }

      let pathParams = {
      };
      let queryParams = {
        'location': location,
        'typ': typ,
        'nr': nr
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Status;
      return this.apiClient.callApi(
        '/device', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCreditJournal operation.
     * @callback module:api/DefaultApi~getCreditJournalCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreditJournal} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a journal of all credits from and to date
     * @param {Number} from UTC timestamp start from
     * @param {Number} to UTC timestamp end at
     * @param {Object} opts Optional parameters
     * @param {String} [cardId] 
     * @param {module:api/DefaultApi~getCreditJournalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreditJournal}
     */
    getCreditJournal(from, to, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling getCreditJournal");
      }
      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling getCreditJournal");
      }

      let pathParams = {
      };
      let queryParams = {
        'from': from,
        'to': to,
        'card_id': opts['cardId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CreditJournal;
      return this.apiClient.callApi(
        '/credit_journal', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCustomer operation.
     * @callback module:api/DefaultApi~getCustomerCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Customer} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a customer with credit info
     * @param {String} id the unique 9 characters card ID
     * @param {module:api/DefaultApi~getCustomerCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Customer}
     */
    getCustomer(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getCustomer");
      }

      let pathParams = {
      };
      let queryParams = {
        'id': id
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Customer;
      return this.apiClient.callApi(
        '/customer', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDevice operation.
     * @callback module:api/DefaultApi~getDeviceCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Device>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a device
     * @param {String} location The shop location ID
     * @param {String} typ The type of the device
     * @param {Number} nr The number of the device
     * @param {module:api/DefaultApi~getDeviceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Device>}
     */
    getDevice(location, typ, nr, callback) {
      let postBody = null;
      // verify the required parameter 'location' is set
      if (location === undefined || location === null) {
        throw new Error("Missing the required parameter 'location' when calling getDevice");
      }
      // verify the required parameter 'typ' is set
      if (typ === undefined || typ === null) {
        throw new Error("Missing the required parameter 'typ' when calling getDevice");
      }
      // verify the required parameter 'nr' is set
      if (nr === undefined || nr === null) {
        throw new Error("Missing the required parameter 'nr' when calling getDevice");
      }

      let pathParams = {
      };
      let queryParams = {
        'location': location,
        'typ': typ,
        'nr': nr
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Device];
      return this.apiClient.callApi(
        '/device', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDeviceInfo operation.
     * @callback module:api/DefaultApi~getDeviceInfoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeviceInfo} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a device information
     * @param {String} location The shop location ID
     * @param {String} typ The type of the device
     * @param {Number} nr The number of the device
     * @param {module:api/DefaultApi~getDeviceInfoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeviceInfo}
     */
    getDeviceInfo(location, typ, nr, callback) {
      let postBody = null;
      // verify the required parameter 'location' is set
      if (location === undefined || location === null) {
        throw new Error("Missing the required parameter 'location' when calling getDeviceInfo");
      }
      // verify the required parameter 'typ' is set
      if (typ === undefined || typ === null) {
        throw new Error("Missing the required parameter 'typ' when calling getDeviceInfo");
      }
      // verify the required parameter 'nr' is set
      if (nr === undefined || nr === null) {
        throw new Error("Missing the required parameter 'nr' when calling getDeviceInfo");
      }

      let pathParams = {
      };
      let queryParams = {
        'location': location,
        'typ': typ,
        'nr': nr
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeviceInfo;
      return this.apiClient.callApi(
        '/device_info', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDevices operation.
     * @callback module:api/DefaultApi~getDevicesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Device>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns list of device
     * @param {Object} opts Optional parameters
     * @param {String} [location] The shop location ID as a filter - if not given or empty devices of all shops are returned
     * @param {module:api/DefaultApi~getDevicesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Device>}
     */
    getDevices(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'location': opts['location']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Device];
      return this.apiClient.callApi(
        '/devices', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getLocation operation.
     * @callback module:api/DefaultApi~getLocationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Location} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a location
     * @param {String} id the unique location ID
     * @param {module:api/DefaultApi~getLocationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Location}
     */
    getLocation(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getLocation");
      }

      let pathParams = {
      };
      let queryParams = {
        'id': id
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Location;
      return this.apiClient.callApi(
        '/location', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getLocations operation.
     * @callback module:api/DefaultApi~getLocationsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Location>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns list of locations
     * @param {module:api/DefaultApi~getLocationsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Location>}
     */
    getLocations(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Location];
      return this.apiClient.callApi(
        '/locations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPayments operation.
     * @callback module:api/DefaultApi~getPaymentsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Payment>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a list of payments
     * @param {Number} from UTC timestamp start from
     * @param {Number} to UTC timestamp end at
     * @param {module:api/DefaultApi~getPaymentsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Payment>}
     */
    getPayments(from, to, callback) {
      let postBody = null;
      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling getPayments");
      }
      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling getPayments");
      }

      let pathParams = {
      };
      let queryParams = {
        'from': from,
        'to': to
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Payment];
      return this.apiClient.callApi(
        '/payments', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPriceLine operation.
     * @callback module:api/DefaultApi~getPriceLineCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PriceLine} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a price line
     * @param {String} id the unique price line ID
     * @param {module:api/DefaultApi~getPriceLineCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PriceLine}
     */
    getPriceLine(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getPriceLine");
      }

      let pathParams = {
      };
      let queryParams = {
        'id': id
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PriceLine;
      return this.apiClient.callApi(
        '/price_line', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPriceLines operation.
     * @callback module:api/DefaultApi~getPriceLinesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PriceLine>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns list of price lines
     * @param {module:api/DefaultApi~getPriceLinesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/PriceLine>}
     */
    getPriceLines(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PriceLine];
      return this.apiClient.callApi(
        '/price_lines', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the moduleProgramm operation.
     * @callback module:api/DefaultApi~moduleProgrammCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModuleProgramm200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} typ 
     * @param {String} version 
     * @param {File} file 
     * @param {module:api/DefaultApi~moduleProgrammCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModuleProgramm200Response}
     */
    moduleProgramm(typ, version, file, callback) {
      let postBody = null;
      // verify the required parameter 'typ' is set
      if (typ === undefined || typ === null) {
        throw new Error("Missing the required parameter 'typ' when calling moduleProgramm");
      }
      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling moduleProgramm");
      }
      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling moduleProgramm");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'typ': typ,
        'version': version,
        'file': file
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = ModuleProgramm200Response;
      return this.apiClient.callApi(
        '/module_programm', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the newDevice operation.
     * @callback module:api/DefaultApi~newDeviceCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a new device
     * @param {module:model/Device} device The device object to be created
     * @param {module:api/DefaultApi~newDeviceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Status}
     */
    newDevice(device, callback) {
      let postBody = device;
      // verify the required parameter 'device' is set
      if (device === undefined || device === null) {
        throw new Error("Missing the required parameter 'device' when calling newDevice");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Status;
      return this.apiClient.callApi(
        '/device', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the newLocation operation.
     * @callback module:api/DefaultApi~newLocationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a new location
     * @param {module:model/Location} location The location object to be created
     * @param {module:api/DefaultApi~newLocationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Status}
     */
    newLocation(location, callback) {
      let postBody = location;
      // verify the required parameter 'location' is set
      if (location === undefined || location === null) {
        throw new Error("Missing the required parameter 'location' when calling newLocation");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Status;
      return this.apiClient.callApi(
        '/location', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the newPriceLine operation.
     * @callback module:api/DefaultApi~newPriceLineCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a new price line
     * @param {module:model/PriceLine} priceLine The price line object to be created
     * @param {module:api/DefaultApi~newPriceLineCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Status}
     */
    newPriceLine(priceLine, callback) {
      let postBody = priceLine;
      // verify the required parameter 'priceLine' is set
      if (priceLine === undefined || priceLine === null) {
        throw new Error("Missing the required parameter 'priceLine' when calling newPriceLine");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Status;
      return this.apiClient.callApi(
        '/price_line', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the payment operation.
     * @callback module:api/DefaultApi~paymentCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds a credit journal entry and updates the customer's credit
     * @param {module:model/PaymentRequest} paymentRequest 
     * @param {module:api/DefaultApi~paymentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Status}
     */
    payment(paymentRequest, callback) {
      let postBody = paymentRequest;
      // verify the required parameter 'paymentRequest' is set
      if (paymentRequest === undefined || paymentRequest === null) {
        throw new Error("Missing the required parameter 'paymentRequest' when calling payment");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Status;
      return this.apiClient.callApi(
        '/payment', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the robotsTxtGet operation.
     * @callback module:api/DefaultApi~robotsTxtGetCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns robots.txt
     * @param {module:api/DefaultApi~robotsTxtGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    robotsTxtGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/robots.txt', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the testGet operation.
     * @callback module:api/DefaultApi~testGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns OK
     * @param {module:api/DefaultApi~testGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Status}
     */
    testGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Status;
      return this.apiClient.callApi(
        '/test', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the topupCredit operation.
     * @callback module:api/DefaultApi~topupCreditCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds a credit journal entry and updates the customer's credit
     * @param {module:model/TopupCreditRequest} topupCreditRequest 
     * @param {module:api/DefaultApi~topupCreditCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Status}
     */
    topupCredit(topupCreditRequest, callback) {
      let postBody = topupCreditRequest;
      // verify the required parameter 'topupCreditRequest' is set
      if (topupCreditRequest === undefined || topupCreditRequest === null) {
        throw new Error("Missing the required parameter 'topupCreditRequest' when calling topupCredit");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Status;
      return this.apiClient.callApi(
        '/topup_credit', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateCustomer operation.
     * @callback module:api/DefaultApi~updateCustomerCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates the customer's name and active status
     * @param {String} id The unique 9 characters card ID
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateCustomerRequest} [updateCustomerRequest] 
     * @param {module:api/DefaultApi~updateCustomerCallback} callback The callback function, accepting three arguments: error, data, response
     */
    updateCustomer(id, opts, callback) {
      opts = opts || {};
      let postBody = opts['updateCustomerRequest'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateCustomer");
      }

      let pathParams = {
      };
      let queryParams = {
        'id': id
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/customer', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateDevice operation.
     * @callback module:api/DefaultApi~updateDeviceCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Device} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates an existing device
     * @param {module:model/Device} device The updated device object
     * @param {module:api/DefaultApi~updateDeviceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Device}
     */
    updateDevice(device, callback) {
      let postBody = device;
      // verify the required parameter 'device' is set
      if (device === undefined || device === null) {
        throw new Error("Missing the required parameter 'device' when calling updateDevice");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Device;
      return this.apiClient.callApi(
        '/device', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateModuleBinary operation.
     * @callback module:api/DefaultApi~updateModuleBinaryCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} version 
     * @param {String} mac 
     * @param {module:api/DefaultApi~updateModuleBinaryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    updateModuleBinary(version, mac, callback) {
      let postBody = null;
      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling updateModuleBinary");
      }
      // verify the required parameter 'mac' is set
      if (mac === undefined || mac === null) {
        throw new Error("Missing the required parameter 'mac' when calling updateModuleBinary");
      }

      let pathParams = {
        'version': version,
        'mac': mac
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/octet-stream', 'application/json'];
      let returnType = File;
      return this.apiClient.callApi(
        '/update_module_binary/{mac}/{version}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
