/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import CreditJournal from '../model/CreditJournal';
import Customer from '../model/Customer';
import CustomerBody from '../model/CustomerBody';
import Device from '../model/Device';
import DeviceInfo from '../model/DeviceInfo';
import Location from '../model/Location';
import Payment from '../model/Payment';
import PaymentBody from '../model/PaymentBody';
import PriceLine from '../model/PriceLine';
import Status from '../model/Status';
import TopupCreditBody from '../model/TopupCreditBody';

/**
* Default service.
* @module api/DefaultApi
* @version 0.1.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addCreditJournal operation.
     * @callback moduleapi/DefaultApi~addCreditJournalCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds new lines to the journal for credits or deductions.
     * @param {Array.<module:model/CreditJournal>} body 
     * @param {module:api/DefaultApi~addCreditJournalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    addCreditJournal(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addCreditJournal");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Status;

      return this.apiClient.callApi(
        '/credit_journal', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the allowStart operation.
     * @callback moduleapi/DefaultApi~allowStartCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Allows the start of a washer or dryer
     * @param {String} name The name of the device
     * @param {Number} value value / ms or count
     * @param {module:api/DefaultApi~allowStartCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    allowStart(name, value, callback) {
      
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling allowStart");
      }
      // verify the required parameter 'value' is set
      if (value === undefined || value === null) {
        throw new Error("Missing the required parameter 'value' when calling allowStart");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'name': name,'value': value
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Status;

      return this.apiClient.callApi(
        '/allowstart', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getCreditJournal operation.
     * @callback moduleapi/DefaultApi~getCreditJournalCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreditJournal{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a journal of all credits from and to date
     * @param {Number} from UTC timestamp start from
     * @param {Number} to UTC timestamp end at
     * @param {Object} opts Optional parameters
     * @param {String} opts.cardId 
     * @param {module:api/DefaultApi~getCreditJournalCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getCreditJournal(from, to, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling getCreditJournal");
      }
      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling getCreditJournal");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'from': from,'to': to,'card_id': opts['cardId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CreditJournal;

      return this.apiClient.callApi(
        '/credit_journal', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getCustomer operation.
     * @callback moduleapi/DefaultApi~getCustomerCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Customer{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a customer with credit info
     * @param {String} id the unique 9 characters card ID
     * @param {module:api/DefaultApi~getCustomerCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getCustomer(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getCustomer");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'id': id
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Customer;

      return this.apiClient.callApi(
        '/customer', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getCustomerAccount operation.
     * @callback moduleapi/DefaultApi~getCustomerAccountCallback
     * @param {String} error Error message, if any.
     * @param {'String'{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the customers user account
     * @param {String} cardId 
     * @param {module:api/DefaultApi~getCustomerAccountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getCustomerAccount(cardId, callback) {
      
      let postBody = null;
      // verify the required parameter 'cardId' is set
      if (cardId === undefined || cardId === null) {
        throw new Error("Missing the required parameter 'cardId' when calling getCustomerAccount");
      }

      let pathParams = {
        'card_id': cardId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['text/html'];
      let returnType = 'String';

      return this.apiClient.callApi(
        '/B/{card_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getDevice operation.
     * @callback moduleapi/DefaultApi~getDeviceCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a device
     * @param {String} name The name that describes the specific module &#x3D; Country+ShopId+moduleId
     * @param {module:api/DefaultApi~getDeviceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getDevice(name, callback) {
      
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling getDevice");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'name': name
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Status;

      return this.apiClient.callApi(
        '/device', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getDeviceInfo operation.
     * @callback moduleapi/DefaultApi~getDeviceInfoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeviceInfo{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a device information
     * @param {String} name The name that identifies the device
     * @param {module:api/DefaultApi~getDeviceInfoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getDeviceInfo(name, callback) {
      
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling getDeviceInfo");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'name': name
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeviceInfo;

      return this.apiClient.callApi(
        '/device_info', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getDevices operation.
     * @callback moduleapi/DefaultApi~getDevicesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Device>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns list of device
     * @param {Object} opts Optional parameters
     * @param {String} opts.location The shop location ID as a filter - if not given or empty devices of all shops are returned
     * @param {module:api/DefaultApi~getDevicesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getDevices(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'location': opts['location']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Device];

      return this.apiClient.callApi(
        '/devices', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getLocation operation.
     * @callback moduleapi/DefaultApi~getLocationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Location{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a location
     * @param {String} id the unique location ID
     * @param {module:api/DefaultApi~getLocationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getLocation(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getLocation");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'id': id
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Location;

      return this.apiClient.callApi(
        '/location', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getLocations operation.
     * @callback moduleapi/DefaultApi~getLocationsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Location>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns list of locations
     * @param {module:api/DefaultApi~getLocationsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getLocations(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Location];

      return this.apiClient.callApi(
        '/locations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getPayments operation.
     * @callback moduleapi/DefaultApi~getPaymentsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Payment>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a list of payments
     * @param {Number} from UTC timestamp start from
     * @param {Number} to UTC timestamp end at
     * @param {module:api/DefaultApi~getPaymentsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getPayments(from, to, callback) {
      
      let postBody = null;
      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling getPayments");
      }
      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling getPayments");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'from': from,'to': to
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Payment];

      return this.apiClient.callApi(
        '/payments', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getPriceLine operation.
     * @callback moduleapi/DefaultApi~getPriceLineCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PriceLine{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a price line
     * @param {String} id the unique price line ID
     * @param {module:api/DefaultApi~getPriceLineCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getPriceLine(id, callback) {
      
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getPriceLine");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'id': id
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PriceLine;

      return this.apiClient.callApi(
        '/price_line', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getPriceLines operation.
     * @callback moduleapi/DefaultApi~getPriceLinesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PriceLine>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns list of price lines
     * @param {module:api/DefaultApi~getPriceLinesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getPriceLines(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PriceLine];

      return this.apiClient.callApi(
        '/price_lines', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the newDevice operation.
     * @callback moduleapi/DefaultApi~newDeviceCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a new device
     * @param {module:model/Device} body The device object to be created
     * @param {module:api/DefaultApi~newDeviceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    newDevice(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling newDevice");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Status;

      return this.apiClient.callApi(
        '/device', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the newLocation operation.
     * @callback moduleapi/DefaultApi~newLocationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a new location
     * @param {module:model/Location} body The location object to be created
     * @param {module:api/DefaultApi~newLocationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    newLocation(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling newLocation");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Status;

      return this.apiClient.callApi(
        '/location', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the newPriceLine operation.
     * @callback moduleapi/DefaultApi~newPriceLineCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a new price line
     * @param {module:model/PriceLine} body The price line object to be created
     * @param {module:api/DefaultApi~newPriceLineCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    newPriceLine(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling newPriceLine");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Status;

      return this.apiClient.callApi(
        '/price_line', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the payment operation.
     * @callback moduleapi/DefaultApi~paymentCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds a credit journal entry and updates the customer&#x27;s credit
     * @param {module:model/PaymentBody} body 
     * @param {module:api/DefaultApi~paymentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    payment(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling payment");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Status;

      return this.apiClient.callApi(
        '/payment', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the robotsTxtGet operation.
     * @callback moduleapi/DefaultApi~robotsTxtGetCallback
     * @param {String} error Error message, if any.
     * @param {'String'{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns robots.txt
     * @param {module:api/DefaultApi~robotsTxtGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    robotsTxtGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain'];
      let returnType = 'String';

      return this.apiClient.callApi(
        '/robots.txt', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the testGet operation.
     * @callback moduleapi/DefaultApi~testGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns OK
     * @param {module:api/DefaultApi~testGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    testGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Status;

      return this.apiClient.callApi(
        '/test', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the topupCredit operation.
     * @callback moduleapi/DefaultApi~topupCreditCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Status{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds a credit journal entry and updates the customer&#x27;s credit
     * @param {module:model/TopupCreditBody} body 
     * @param {module:api/DefaultApi~topupCreditCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    topupCredit(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling topupCredit");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Status;

      return this.apiClient.callApi(
        '/topup_credit', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the updateCustomer operation.
     * @callback moduleapi/DefaultApi~updateCustomerCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates the customer&#x27;s name and active status
     * @param {String} id The unique 9 characters card ID
     * @param {Object} opts Optional parameters
     * @param {module:model/CustomerBody} opts.body 
     * @param {module:api/DefaultApi~updateCustomerCallback} callback The callback function, accepting three arguments: error, data, response
     */
    updateCustomer(id, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateCustomer");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'id': id
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/customer', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the updateDevice operation.
     * @callback moduleapi/DefaultApi~updateDeviceCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Device{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates an existing device
     * @param {module:model/Device} body The updated device object
     * @param {module:api/DefaultApi~updateDeviceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    updateDevice(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateDevice");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BasicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Device;

      return this.apiClient.callApi(
        '/device', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}