/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import CreditJournal from './model/CreditJournal';
import Customer from './model/Customer';
import CustomerBody from './model/CustomerBody';
import Device from './model/Device';
import DeviceInfo from './model/DeviceInfo';
import DeviceStatus from './model/DeviceStatus';
import InlineResponse201 from './model/InlineResponse201';
import Module from './model/Module';
import Pump from './model/Pump';
import Status from './model/Status';
import DefaultApi from './api/DefaultApi';

/**
* Bubble_Point_System_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Bps = require('index'); // See note below*.
* var xxxSvc = new Bps.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Bps.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Bps.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Bps.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreditJournal model constructor.
     * @property {module:model/CreditJournal}
     */
    CreditJournal,

    /**
     * The Customer model constructor.
     * @property {module:model/Customer}
     */
    Customer,

    /**
     * The CustomerBody model constructor.
     * @property {module:model/CustomerBody}
     */
    CustomerBody,

    /**
     * The Device model constructor.
     * @property {module:model/Device}
     */
    Device,

    /**
     * The DeviceInfo model constructor.
     * @property {module:model/DeviceInfo}
     */
    DeviceInfo,

    /**
     * The DeviceStatus model constructor.
     * @property {module:model/DeviceStatus}
     */
    DeviceStatus,

    /**
     * The InlineResponse201 model constructor.
     * @property {module:model/InlineResponse201}
     */
    InlineResponse201,

    /**
     * The Module model constructor.
     * @property {module:model/Module}
     */
    Module,

    /**
     * The Pump model constructor.
     * @property {module:model/Pump}
     */
    Pump,

    /**
     * The Status model constructor.
     * @property {module:model/Status}
     */
    Status,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
