import { useAuth } from "./useAuth.js";

const { api, updateAuth } = useAuth();

export function usePayment() {
    const topUp = async (card_id, amount, details, typ, clerk) => {
        // Ensure client is authenticated before making the API call
        const topUpBody = {
            timestamp: 0, // is generated by the server
            card_id: card_id,
            amount: amount,
            bill_nr: "", // is generated by the server
            paypal_details: details,
            typ: typ,
            clerk: clerk,
        };
        return new Promise((resolve, reject) => {
            api.topupCredit(topUpBody, (error, data) => {
                if (error) {
                    reject(error)
                } else {
                    resolve(data);
                }
            });
        })
    };

    const payment = async (paymentBody) => {
        if (paymentBody.card_id=='anonym'){
            updateAuth(null);
        } else {
            updateAuth(paymentBody.card_id);
        }
        return new Promise((resolve, reject) => {
            api.payment([paymentBody], (error, data) => {
                if (error) {
                    reject(error)
                } else {
                    resolve(data);
                }
            });
        })
    }

    const payments = async (card_id, from, to) => {
        updateAuth(card_id);
        return new Promise((resolve, reject) => {
            var opts = {
                from: from,
                to: to,
            }
            api.getUserPayments(card_id, opts, (error, data) => {
                if (error) {
                    reject(error)
                } else {
                    resolve(data);
                }
            })
        })
    }

    const allowStart = (name, duration) => {
        api.allowStart(name, duration,
            (error, data, response) => {
                if (error) {
                    console.error(error);
                    return;
                } 
                console.log("allowStart", response);
            }
        );
    };

    return {
        topUp,
        allowStart,
        payment,
        payments,
    };
}