/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Binary model module.
 * @module model/Binary
 * @version 0.1.0
 */
export default class Binary {
  /**
   * Constructs a new <code>Binary</code>.
   * @alias module:model/Binary
   * @class
   * @param type {String} 
   * @param binary {String} module programm binary
   */
  constructor(type, binary) {
    this.type = type;
    this.binary = binary;
  }

  /**
   * Constructs a <code>Binary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Binary} obj Optional instance to populate.
   * @return {module:model/Binary} The populated <code>Binary</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Binary();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('binary'))
        obj.binary = ApiClient.convertToType(data['binary'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} type
 */
Binary.prototype.type = undefined;

/**
 * module programm binary
 * @member {String} binary
 */
Binary.prototype.binary = undefined;

