/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreditJournal model module.
 * @module model/CreditJournal
 * @version 0.1.0
 */
export default class CreditJournal {
  /**
   * Constructs a new <code>CreditJournal</code>.
   * @alias module:model/CreditJournal
   * @class
   * @param cardId {String} 
   * @param amount {Number} amount in cent; negative deducts from credit; positive adds to credit
   * @param billNr {String} bill nr is generated by the API using current date and time
   */
  constructor(cardId, amount, billNr) {
    this.cardId = cardId;
    this.amount = amount;
    this.billNr = billNr;
  }

  /**
   * Constructs a <code>CreditJournal</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreditJournal} obj Optional instance to populate.
   * @return {module:model/CreditJournal} The populated <code>CreditJournal</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreditJournal();
      if (data.hasOwnProperty('card_id'))
        obj.cardId = ApiClient.convertToType(data['card_id'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('bill_nr'))
        obj.billNr = ApiClient.convertToType(data['bill_nr'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} cardId
 */
CreditJournal.prototype.cardId = undefined;

/**
 * amount in cent; negative deducts from credit; positive adds to credit
 * @member {Number} amount
 */
CreditJournal.prototype.amount = undefined;

/**
 * bill nr is generated by the API using current date and time
 * @member {String} billNr
 */
CreditJournal.prototype.billNr = undefined;

