/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Customer model module.
 * @module model/Customer
 * @version 0.1.0
 */
export default class Customer {
  /**
   * Constructs a new <code>Customer</code>.
   * @alias module:model/Customer
   * @class
   * @param id {String} 
   * @param name {String} 
   * @param active {Boolean} 
   * @param credit {Number} credit amout in euro cent
   */
  constructor(id, name, active, credit) {
    this.id = id;
    this.name = name;
    this.active = active;
    this.credit = credit;
  }

  /**
   * Constructs a <code>Customer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Customer} obj Optional instance to populate.
   * @return {module:model/Customer} The populated <code>Customer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Customer();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('active'))
        obj.active = ApiClient.convertToType(data['active'], 'Boolean');
      if (data.hasOwnProperty('credit'))
        obj.credit = ApiClient.convertToType(data['credit'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Customer.prototype.id = undefined;

/**
 * @member {String} name
 */
Customer.prototype.name = undefined;

/**
 * @member {Boolean} active
 */
Customer.prototype.active = undefined;

/**
 * credit amout in euro cent
 * @member {Number} credit
 */
Customer.prototype.credit = undefined;

