/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DeviceStatus model module.
 * @module model/DeviceStatus
 * @version 0.1.0
 */
export default class DeviceStatus {
  /**
   * Constructs a new <code>DeviceStatus</code>.
   * @alias module:model/DeviceStatus
   * @class
   * @param allowStart {Boolean} 
   * @param busy {Boolean} 
   * @param wantDetergent {Boolean} 
   * @param wantSoftener {Boolean} 
   */
  constructor(allowStart, busy, wantDetergent, wantSoftener) {
    this.allowStart = allowStart;
    this.busy = busy;
    this.wantDetergent = wantDetergent;
    this.wantSoftener = wantSoftener;
  }

  /**
   * Constructs a <code>DeviceStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceStatus} obj Optional instance to populate.
   * @return {module:model/DeviceStatus} The populated <code>DeviceStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeviceStatus();
      if (data.hasOwnProperty('allow_start'))
        obj.allowStart = ApiClient.convertToType(data['allow_start'], 'Boolean');
      if (data.hasOwnProperty('busy'))
        obj.busy = ApiClient.convertToType(data['busy'], 'Boolean');
      if (data.hasOwnProperty('want_detergent'))
        obj.wantDetergent = ApiClient.convertToType(data['want_detergent'], 'Boolean');
      if (data.hasOwnProperty('want_softener'))
        obj.wantSoftener = ApiClient.convertToType(data['want_softener'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Boolean} allowStart
 */
DeviceStatus.prototype.allowStart = undefined;

/**
 * @member {Boolean} busy
 */
DeviceStatus.prototype.busy = undefined;

/**
 * @member {Boolean} wantDetergent
 */
DeviceStatus.prototype.wantDetergent = undefined;

/**
 * @member {Boolean} wantSoftener
 */
DeviceStatus.prototype.wantSoftener = undefined;

