/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import DeviceStatus from './DeviceStatus';
import Module from './Module';
import Pump from './Pump';

/**
 * The Device model module.
 * @module model/Device
 * @version 0.1.0
 */
export default class Device {
  /**
   * Constructs a new <code>Device</code>.
   * @alias module:model/Device
   * @class
   * @param alias {String} 
   * @param type {String} 
   * @param location {String} 
   * @param name {String} 
   * @param module {module:model/Module} 
   * @param detergent {module:model/Pump} 
   * @param softener {module:model/Pump} 
   * @param status {module:model/DeviceStatus} 
   */
  constructor(alias, type, location, name, module, detergent, softener, status) {
    this.alias = alias;
    this.type = type;
    this.location = location;
    this.name = name;
    this.module = module;
    this.detergent = detergent;
    this.softener = softener;
    this.status = status;
  }

  /**
   * Constructs a <code>Device</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Device} obj Optional instance to populate.
   * @return {module:model/Device} The populated <code>Device</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Device();
      if (data.hasOwnProperty('alias'))
        obj.alias = ApiClient.convertToType(data['alias'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('module'))
        obj.module = Module.constructFromObject(data['module']);
      if (data.hasOwnProperty('detergent'))
        obj.detergent = Pump.constructFromObject(data['detergent']);
      if (data.hasOwnProperty('softener'))
        obj.softener = Pump.constructFromObject(data['softener']);
      if (data.hasOwnProperty('status'))
        obj.status = DeviceStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {String} alias
 */
Device.prototype.alias = undefined;

/**
 * @member {String} location
 */
Device.prototype.location = undefined;

/**
 * @member {String} type
 */
Device.prototype.type = undefined;

/**
 * @member {String} name
 */
Device.prototype.name = undefined;

/**
 * @member {module:model/Module} module
 */
Device.prototype.module = undefined;

/**
 * @member {module:model/Pump} detergent
 */
Device.prototype.detergent = undefined;

/**
 * @member {module:model/Pump} softener
 */
Device.prototype.softener = undefined;

/**
 * @member {module:model/DeviceStatus} status
 */
Device.prototype.status = undefined;

