/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DeviceInfo model module.
 * @module model/DeviceInfo
 * @version 0.1.0
 */
export default class DeviceInfo {
  /**
   * Constructs a new <code>DeviceInfo</code>.
   * @alias module:model/DeviceInfo
   * @class
   * @param shop {String} 
   * @param type {String} 
   * @param _number {Number} 
   * @param status {String} 
   * @param price {Number} 
   */
  constructor(shop, type, _number, status, price) {
    this.shop = shop;
    this.type = type;
    this._number = _number;
    this.status = status;
    this.price = price;
  }

  /**
   * Constructs a <code>DeviceInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceInfo} obj Optional instance to populate.
   * @return {module:model/DeviceInfo} The populated <code>DeviceInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeviceInfo();
      if (data.hasOwnProperty('shop'))
        obj.shop = ApiClient.convertToType(data['shop'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('number'))
        obj._number = ApiClient.convertToType(data['number'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} shop
 */
DeviceInfo.prototype.shop = undefined;

/**
 * @member {String} type
 */
DeviceInfo.prototype.type = undefined;

/**
 * @member {Number} _number
 */
DeviceInfo.prototype._number = undefined;

/**
 * @member {String} status
 */
DeviceInfo.prototype.status = undefined;

/**
 * @member {Number} price
 */
DeviceInfo.prototype.price = undefined;

