/**
 * BPS
 * Bubble Point System API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DevicesLastState model module.
 * @module model/DevicesLastState
 * @version 0.1.0
 */
class DevicesLastState {
    /**
     * Constructs a new <code>DevicesLastState</code>.
     * @alias module:model/DevicesLastState
     */
    constructor() { 
        
        DevicesLastState.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DevicesLastState</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DevicesLastState} obj Optional instance to populate.
     * @return {module:model/DevicesLastState} The populated <code>DevicesLastState</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DevicesLastState();

            if (data.hasOwnProperty('nr')) {
                obj['nr'] = ApiClient.convertToType(data['nr'], 'Number');
            }
            if (data.hasOwnProperty('last_state')) {
                obj['last_state'] = ApiClient.convertToType(data['last_state'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DevicesLastState</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DevicesLastState</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['last_state'] && !(typeof data['last_state'] === 'string' || data['last_state'] instanceof String)) {
            throw new Error("Expected the field `last_state` to be a primitive type in the JSON string but got " + data['last_state']);
        }

        return true;
    }


}



/**
 * @member {Number} nr
 */
DevicesLastState.prototype['nr'] = undefined;

/**
 * The last state of the device
 * @member {String} last_state
 */
DevicesLastState.prototype['last_state'] = undefined;






export default DevicesLastState;

