/**
 * BPS
 * Bubble Point System API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DeviceState.
* @enum {}
* @readonly
*/
export default class DeviceState {
    
        /**
         * value: "free"
         * @const
         */
        "DeviceStateFree" = "free";

    
        /**
         * value: "busy"
         * @const
         */
        "DeviceStateBusy" = "busy";

    
        /**
         * value: "payed"
         * @const
         */
        "DeviceStatePayed" = "payed";

    
        /**
         * value: "outoforder"
         * @const
         */
        "DeviceStateOutOfOrder" = "outoforder";

    

    /**
    * Returns a <code>DeviceState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/DeviceState} The enum <code>DeviceState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

