/**
 * BPS
 * Bubble Point System API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Discount model module.
 * @module model/Discount
 * @version 0.1.0
 */
class Discount {
    /**
     * Constructs a new <code>Discount</code>.
     * @alias module:model/Discount
     * @param id {String} 
     * @param percentage {Number} percentage of the discount
     * @param name {String} name of the discount
     * @param userinfo {String} information about the discount for the user
     * @param info {String} internal information about the discount
     */
    constructor(id, percentage, name, userinfo, info) { 
        
        Discount.initialize(this, id, percentage, name, userinfo, info);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, percentage, name, userinfo, info) { 
        obj['id'] = id;
        obj['percentage'] = percentage;
        obj['name'] = name;
        obj['userinfo'] = userinfo;
        obj['info'] = info;
    }

    /**
     * Constructs a <code>Discount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Discount} obj Optional instance to populate.
     * @return {module:model/Discount} The populated <code>Discount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Discount();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('percentage')) {
                obj['percentage'] = ApiClient.convertToType(data['percentage'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('userinfo')) {
                obj['userinfo'] = ApiClient.convertToType(data['userinfo'], 'String');
            }
            if (data.hasOwnProperty('info')) {
                obj['info'] = ApiClient.convertToType(data['info'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Discount</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Discount</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Discount.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['userinfo'] && !(typeof data['userinfo'] === 'string' || data['userinfo'] instanceof String)) {
            throw new Error("Expected the field `userinfo` to be a primitive type in the JSON string but got " + data['userinfo']);
        }
        // ensure the json data is a string
        if (data['info'] && !(typeof data['info'] === 'string' || data['info'] instanceof String)) {
            throw new Error("Expected the field `info` to be a primitive type in the JSON string but got " + data['info']);
        }

        return true;
    }


}

Discount.RequiredProperties = ["id", "percentage", "name", "userinfo", "info"];

/**
 * @member {String} id
 */
Discount.prototype['id'] = undefined;

/**
 * percentage of the discount
 * @member {Number} percentage
 */
Discount.prototype['percentage'] = undefined;

/**
 * name of the discount
 * @member {String} name
 */
Discount.prototype['name'] = undefined;

/**
 * applies for marketing code
 * @member {String} code
 */
Discount.prototype['code'] = undefined;

/**
 * information about the discount for the user
 * @member {String} userinfo
 */
Discount.prototype['userinfo'] = undefined;

/**
 * internal information about the discount
 * @member {String} info
 */
Discount.prototype['info'] = undefined;






export default Discount;

