/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DryerStatus model module.
 * @module model/DryerStatus
 * @version 0.1.0
 */
export default class DryerStatus {
  /**
   * Constructs a new <code>DryerStatus</code>.
   * @alias module:model/DryerStatus
   * @class
   * @param timestamp {Number} 
   * @param info {String} status of the dryer
   */
  constructor(timestamp, info) {
    this.timestamp = timestamp;
    this.info = info;
  }

  /**
   * Constructs a <code>DryerStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DryerStatus} obj Optional instance to populate.
   * @return {module:model/DryerStatus} The populated <code>DryerStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DryerStatus();
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'Number');
      if (data.hasOwnProperty('info'))
        obj.info = ApiClient.convertToType(data['info'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} timestamp
 */
DryerStatus.prototype.timestamp = undefined;

/**
 * status of the dryer
 * @member {String} info
 */
DryerStatus.prototype.info = undefined;

