/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ModulDurations model module.
 * @module model/ModulDurations
 * @version 0.1.0
 */
export default class ModulDurations {
  /**
   * Constructs a new <code>ModulDurations</code>.
   * @alias module:model/ModulDurations
   * @class
   * @param self {Number} duration in 1/10 seconds of impuls
   */
  constructor(self) {
    this.self = self;
  }

  /**
   * Constructs a <code>ModulDurations</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModulDurations} obj Optional instance to populate.
   * @return {module:model/ModulDurations} The populated <code>ModulDurations</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModulDurations();
      if (data.hasOwnProperty('self'))
        obj.self = ApiClient.convertToType(data['self'], 'Number');
      if (data.hasOwnProperty('detergent'))
        obj.detergent = ApiClient.convertToType(data['detergent'], 'Number');
      if (data.hasOwnProperty('softener'))
        obj.softener = ApiClient.convertToType(data['softener'], 'Number');
    }
    return obj;
  }
}

/**
 * duration in 1/10 seconds of impuls
 * @member {Number} self
 */
ModulDurations.prototype.self = undefined;

/**
 * duration in 1/10 seconds of pump running
 * @member {Number} detergent
 */
ModulDurations.prototype.detergent = undefined;

/**
 * duration in 1/10 seconds of pump running
 * @member {Number} softener
 */
ModulDurations.prototype.softener = undefined;

