/**
 * BPS
 * Bubble Point System API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../BpsApiClient';

/**
 * The PaymentRequest model module.
 * @module model/PaymentRequest
 * @version 0.1.0
 */
class PaymentRequest {
    /**
     * Constructs a new <code>PaymentRequest</code>.
     * @alias module:model/PaymentRequest
     * @param billNr {String} The bill number associated with the payment
     * @param machineName {String} The name of the machine
     * @param cardId {String} The unique 9 characters card ID
     * @param amount {Number} The amount to be deducted from the credit in euro cents
     */
    constructor(billNr, machineName, cardId, amount) { 
        
        PaymentRequest.initialize(this, billNr, machineName, cardId, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, billNr, machineName, cardId, amount) { 
        obj['bill_nr'] = billNr;
        obj['machine_name'] = machineName;
        obj['card_id'] = cardId;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>PaymentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentRequest} obj Optional instance to populate.
     * @return {module:model/PaymentRequest} The populated <code>PaymentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentRequest();

            if (data.hasOwnProperty('bill_nr')) {
                obj['bill_nr'] = ApiClient.convertToType(data['bill_nr'], 'String');
            }
            if (data.hasOwnProperty('machine_name')) {
                obj['machine_name'] = ApiClient.convertToType(data['machine_name'], 'String');
            }
            if (data.hasOwnProperty('card_id')) {
                obj['card_id'] = ApiClient.convertToType(data['card_id'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('paypal_details')) {
                obj['paypal_details'] = ApiClient.convertToType(data['paypal_details'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['bill_nr'] && !(typeof data['bill_nr'] === 'string' || data['bill_nr'] instanceof String)) {
            throw new Error("Expected the field `bill_nr` to be a primitive type in the JSON string but got " + data['bill_nr']);
        }
        // ensure the json data is a string
        if (data['machine_name'] && !(typeof data['machine_name'] === 'string' || data['machine_name'] instanceof String)) {
            throw new Error("Expected the field `machine_name` to be a primitive type in the JSON string but got " + data['machine_name']);
        }
        // ensure the json data is a string
        if (data['card_id'] && !(typeof data['card_id'] === 'string' || data['card_id'] instanceof String)) {
            throw new Error("Expected the field `card_id` to be a primitive type in the JSON string but got " + data['card_id']);
        }

        return true;
    }


}

PaymentRequest.RequiredProperties = ["bill_nr", "machine_name", "card_id", "amount"];

/**
 * The bill number associated with the payment
 * @member {String} bill_nr
 */
PaymentRequest.prototype['bill_nr'] = undefined;

/**
 * The name of the machine
 * @member {String} machine_name
 */
PaymentRequest.prototype['machine_name'] = undefined;

/**
 * The unique 9 characters card ID
 * @member {String} card_id
 */
PaymentRequest.prototype['card_id'] = undefined;

/**
 * The amount to be deducted from the credit in euro cents
 * @member {Number} amount
 */
PaymentRequest.prototype['amount'] = undefined;

/**
 * details from the paypal transaction
 * @member {Object} paypal_details
 */
PaymentRequest.prototype['paypal_details'] = undefined;






export default PaymentRequest;

