/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PaymentBody model module.
 * @module model/PaymentBody
 * @version 0.1.0
 */
export default class PaymentBody {
  /**
   * Constructs a new <code>PaymentBody</code>.
   * @alias module:model/PaymentBody
   * @class
   * @param billNr {String} The bill number associated with the payment
   * @param machineName {String} The name of the machine
   * @param cardId {String} The unique 9 characters card ID
   * @param amount {Number} The amount to be deducted from the credit in euro cents
   */
  constructor(billNr, machineName, cardId, amount) {
    this.billNr = billNr;
    this.machineName = machineName;
    this.cardId = cardId;
    this.amount = amount;
  }

  /**
   * Constructs a <code>PaymentBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentBody} obj Optional instance to populate.
   * @return {module:model/PaymentBody} The populated <code>PaymentBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PaymentBody();
      if (data.hasOwnProperty('bill_nr'))
        obj.billNr = ApiClient.convertToType(data['bill_nr'], 'String');
      if (data.hasOwnProperty('machine_name'))
        obj.machineName = ApiClient.convertToType(data['machine_name'], 'String');
      if (data.hasOwnProperty('card_id'))
        obj.cardId = ApiClient.convertToType(data['card_id'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('paypal_details'))
        obj.paypalDetails = ApiClient.convertToType(data['paypal_details'], Object);
    }
    return obj;
  }
}

/**
 * The bill number associated with the payment
 * @member {String} billNr
 */
PaymentBody.prototype.billNr = undefined;

/**
 * The name of the machine
 * @member {String} machineName
 */
PaymentBody.prototype.machineName = undefined;

/**
 * The unique 9 characters card ID
 * @member {String} cardId
 */
PaymentBody.prototype.cardId = undefined;

/**
 * The amount to be deducted from the credit in euro cents
 * @member {Number} amount
 */
PaymentBody.prototype.amount = undefined;

/**
 * details from the paypal transaction
 * @member {Object} paypalDetails
 */
PaymentBody.prototype.paypalDetails = undefined;

