/**
 * BPS
 * Bubble Point System API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Payment from './Payment';

/**
 * The Payment201Response model module.
 * @module model/Payment201Response
 * @version 0.1.0
 */
class Payment201Response {
    /**
     * Constructs a new <code>Payment201Response</code>.
     * @alias module:model/Payment201Response
     */
    constructor() { 
        
        Payment201Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Payment201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Payment201Response} obj Optional instance to populate.
     * @return {module:model/Payment201Response} The populated <code>Payment201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Payment201Response();

            if (data.hasOwnProperty('payments')) {
                obj['payments'] = ApiClient.convertToType(data['payments'], [Payment]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Payment201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Payment201Response</code>.
     */
    static validateJSON(data) {
        if (data['payments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['payments'])) {
                throw new Error("Expected the field `payments` to be an array in the JSON data but got " + data['payments']);
            }
            // validate the optional field `payments` (array)
            for (const item of data['payments']) {
                Payment.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Payment>} payments
 */
Payment201Response.prototype['payments'] = undefined;






export default Payment201Response;

