/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Payment model module.
 * @module model/Payment
 * @version 0.1.0
 */
export default class Payment {
  /**
   * Constructs a new <code>Payment</code>.
   * @alias module:model/Payment
   * @class
   * @param billNr {String} 
   * @param machineName {String} 
   * @param cardId {String} 
   * @param amount {Number} amount in cent; negative deducts from credit; positive adds to credit
   */
  constructor(billNr, machineName, cardId, amount) {
    this.billNr = billNr;
    this.machineName = machineName;
    this.cardId = cardId;
    this.amount = amount;
  }

  /**
   * Constructs a <code>Payment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Payment} obj Optional instance to populate.
   * @return {module:model/Payment} The populated <code>Payment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Payment();
      if (data.hasOwnProperty('bill_nr'))
        obj.billNr = ApiClient.convertToType(data['bill_nr'], 'String');
      if (data.hasOwnProperty('machine_name'))
        obj.machineName = ApiClient.convertToType(data['machine_name'], 'String');
      if (data.hasOwnProperty('card_id'))
        obj.cardId = ApiClient.convertToType(data['card_id'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} billNr
 */
Payment.prototype.billNr = undefined;

/**
 * @member {String} machineName
 */
Payment.prototype.machineName = undefined;

/**
 * @member {String} cardId
 */
Payment.prototype.cardId = undefined;

/**
 * amount in cent; negative deducts from credit; positive adds to credit
 * @member {Number} amount
 */
Payment.prototype.amount = undefined;

