/**
 * BPS
 * Bubble Point System API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PriceLine model module.
 * @module model/PriceLine
 * @version 0.1.0
 */
class PriceLine {
    /**
     * Constructs a new <code>PriceLine</code>.
     * @alias module:model/PriceLine
     * @param id {String} 
     * @param price {Number} gross price in euro cent
     */
    constructor(id, price) { 
        
        PriceLine.initialize(this, id, price);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, price) { 
        obj['id'] = id;
        obj['price'] = price;
    }

    /**
     * Constructs a <code>PriceLine</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PriceLine} obj Optional instance to populate.
     * @return {module:model/PriceLine} The populated <code>PriceLine</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PriceLine();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('dryer_units')) {
                obj['dryer_units'] = ApiClient.convertToType(data['dryer_units'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PriceLine</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PriceLine</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PriceLine.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}

PriceLine.RequiredProperties = ["id", "price"];

/**
 * @member {String} id
 */
PriceLine.prototype['id'] = undefined;

/**
 * gross price in euro cent
 * @member {Number} price
 */
PriceLine.prototype['price'] = undefined;

/**
 * number of dryer units
 * @member {Number} dryer_units
 */
PriceLine.prototype['dryer_units'] = undefined;






export default PriceLine;

