/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PriceLine model module.
 * @module model/PriceLine
 * @version 0.1.0
 */
export default class PriceLine {
  /**
   * Constructs a new <code>PriceLine</code>.
   * @alias module:model/PriceLine
   * @class
   * @param id {String} 
   * @param price {Number} gross price in euro cent
   */
  constructor(id, price) {
    this.id = id;
    this.price = price;
  }

  /**
   * Constructs a <code>PriceLine</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PriceLine} obj Optional instance to populate.
   * @return {module:model/PriceLine} The populated <code>PriceLine</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PriceLine();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
PriceLine.prototype.id = undefined;

/**
 * gross price in euro cent
 * @member {Number} price
 */
PriceLine.prototype.price = undefined;

