/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Pump model module.
 * @module model/Pump
 * @version 0.1.0
 */
export default class Pump {
  /**
   * Constructs a new <code>Pump</code>.
   * @alias module:model/Pump
   * @class
   * @param id {String} id of the pump relay
   * @param nr {Number} number of the pump on the pump relay
   * @param timestamp {Number} last started (will be timely restricted)
   * @param count {Number} count will be restricted in times started)
   */
  constructor(id, nr, timestamp, count) {
    this.id = id;
    this.nr = nr;
    this.timestamp = timestamp;
    this.count = count;
  }

  /**
   * Constructs a <code>Pump</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Pump} obj Optional instance to populate.
   * @return {module:model/Pump} The populated <code>Pump</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Pump();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('nr'))
        obj.nr = ApiClient.convertToType(data['nr'], 'Number');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'Number');
      if (data.hasOwnProperty('count'))
        obj.count = ApiClient.convertToType(data['count'], 'Number');
    }
    return obj;
  }
}

/**
 * id of the pump relay
 * @member {String} id
 */
Pump.prototype.id = undefined;

/**
 * number of the pump on the pump relay
 * @member {Number} nr
 */
Pump.prototype.nr = undefined;

/**
 * last started (will be timely restricted)
 * @member {Number} timestamp
 */
Pump.prototype.timestamp = undefined;

/**
 * count will be restricted in times started)
 * @member {Number} count
 */
Pump.prototype.count = undefined;

