/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Module from './Module';
import PumpRelayStatus from './PumpRelayStatus';

/**
 * The PumpRelay model module.
 * @module model/PumpRelay
 * @version 0.1.0
 */
export default class PumpRelay {
  /**
   * Constructs a new <code>PumpRelay</code>.
   * is a module with an array of pump relays
   * @alias module:model/PumpRelay
   * @class
   * @param id {Number} 
   * @param location {String} 
   * @param module {module:model/Module} 
   * @param status {module:model/PumpRelayStatus} 
   */
  constructor(id, location, module, status) {
    this.id = id;
    this.location = location;
    this.module = module;
    this.status = status;
  }

  /**
   * Constructs a <code>PumpRelay</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PumpRelay} obj Optional instance to populate.
   * @return {module:model/PumpRelay} The populated <code>PumpRelay</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PumpRelay();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('module'))
        obj.module = Module.constructFromObject(data['module']);
      if (data.hasOwnProperty('status'))
        obj.status = PumpRelayStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
PumpRelay.prototype.id = undefined;

/**
 * @member {String} location
 */
PumpRelay.prototype.location = undefined;

/**
 * @member {module:model/Module} module
 */
PumpRelay.prototype.module = undefined;

/**
 * @member {module:model/PumpRelayStatus} status
 */
PumpRelay.prototype.status = undefined;

