/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PumpRelayStatus model module.
 * @module model/PumpRelayStatus
 * @version 0.1.0
 */
export default class PumpRelayStatus {
  /**
   * Constructs a new <code>PumpRelayStatus</code>.
   * @alias module:model/PumpRelayStatus
   * @class
   * @param timestamp {Number} 
   * @param relays {String} status of the indivitual relays
   */
  constructor(timestamp, relays) {
    this.timestamp = timestamp;
    this.relays = relays;
  }

  /**
   * Constructs a <code>PumpRelayStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PumpRelayStatus} obj Optional instance to populate.
   * @return {module:model/PumpRelayStatus} The populated <code>PumpRelayStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PumpRelayStatus();
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'Number');
      if (data.hasOwnProperty('relays'))
        obj.relays = ApiClient.convertToType(data['relays'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} timestamp
 */
PumpRelayStatus.prototype.timestamp = undefined;

/**
 * status of the indivitual relays
 * @member {String} relays
 */
PumpRelayStatus.prototype.relays = undefined;

