/**
 * BPS
 * Bubble Point System API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../BpsApiClient';

/**
 * The TopupCreditRequest model module.
 * @module model/TopupCreditRequest
 * @version 0.1.0
 */
class TopupCreditRequest {
    /**
     * Constructs a new <code>TopupCreditRequest</code>.
     * @alias module:model/TopupCreditRequest
     * @param cardId {String} The unique 9 characters card ID
     * @param amount {Number} The amount to be added to the credit in euro cents
     * @param billNr {String} The bill number associated with the top-up
     */
    constructor(cardId, amount, billNr) { 
        
        TopupCreditRequest.initialize(this, cardId, amount, billNr);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cardId, amount, billNr) { 
        obj['card_id'] = cardId;
        obj['amount'] = amount;
        obj['bill_nr'] = billNr;
    }

    /**
     * Constructs a <code>TopupCreditRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TopupCreditRequest} obj Optional instance to populate.
     * @return {module:model/TopupCreditRequest} The populated <code>TopupCreditRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TopupCreditRequest();

            if (data.hasOwnProperty('card_id')) {
                obj['card_id'] = ApiClient.convertToType(data['card_id'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('bill_nr')) {
                obj['bill_nr'] = ApiClient.convertToType(data['bill_nr'], 'String');
            }
            if (data.hasOwnProperty('paypal_details')) {
                obj['paypal_details'] = ApiClient.convertToType(data['paypal_details'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TopupCreditRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TopupCreditRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TopupCreditRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['card_id'] && !(typeof data['card_id'] === 'string' || data['card_id'] instanceof String)) {
            throw new Error("Expected the field `card_id` to be a primitive type in the JSON string but got " + data['card_id']);
        }
        // ensure the json data is a string
        if (data['bill_nr'] && !(typeof data['bill_nr'] === 'string' || data['bill_nr'] instanceof String)) {
            throw new Error("Expected the field `bill_nr` to be a primitive type in the JSON string but got " + data['bill_nr']);
        }

        return true;
    }


}

TopupCreditRequest.RequiredProperties = ["card_id", "amount", "bill_nr"];

/**
 * The unique 9 characters card ID
 * @member {String} card_id
 */
TopupCreditRequest.prototype['card_id'] = undefined;

/**
 * The amount to be added to the credit in euro cents
 * @member {Number} amount
 */
TopupCreditRequest.prototype['amount'] = undefined;

/**
 * The bill number associated with the top-up
 * @member {String} bill_nr
 */
TopupCreditRequest.prototype['bill_nr'] = undefined;

/**
 * details from the paypal transaction
 * @member {Object} paypal_details
 */
TopupCreditRequest.prototype['paypal_details'] = undefined;






export default TopupCreditRequest;

