/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TopupCreditBody model module.
 * @module model/TopupCreditBody
 * @version 0.1.0
 */
export default class TopupCreditBody {
  /**
   * Constructs a new <code>TopupCreditBody</code>.
   * @alias module:model/TopupCreditBody
   * @class
   * @param cardId {String} The unique 9 characters card ID
   * @param amount {Number} The amount to be added to the credit in euro cents
   * @param billNr {String} The bill number associated with the top-up
   */
  constructor(cardId, amount, billNr) {
    this.cardId = cardId;
    this.amount = amount;
    this.billNr = billNr;
  }

  /**
   * Constructs a <code>TopupCreditBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TopupCreditBody} obj Optional instance to populate.
   * @return {module:model/TopupCreditBody} The populated <code>TopupCreditBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TopupCreditBody();
      if (data.hasOwnProperty('card_id'))
        obj.cardId = ApiClient.convertToType(data['card_id'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('bill_nr'))
        obj.billNr = ApiClient.convertToType(data['bill_nr'], 'String');
      if (data.hasOwnProperty('paypal_details'))
        obj.paypalDetails = ApiClient.convertToType(data['paypal_details'], Object);
    }
    return obj;
  }
}

/**
 * The unique 9 characters card ID
 * @member {String} cardId
 */
TopupCreditBody.prototype.cardId = undefined;

/**
 * The amount to be added to the credit in euro cents
 * @member {Number} amount
 */
TopupCreditBody.prototype.amount = undefined;

/**
 * The bill number associated with the top-up
 * @member {String} billNr
 */
TopupCreditBody.prototype.billNr = undefined;

/**
 * details from the paypal transaction
 * @member {Object} paypalDetails
 */
TopupCreditBody.prototype.paypalDetails = undefined;

