/**
 * BPS
 * Bubble Point System API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreditJournal from './CreditJournal';
import Payment from './Payment';

/**
 * The TopupCredit201Response model module.
 * @module model/TopupCredit201Response
 * @version 0.1.0
 */
class TopupCredit201Response {
    /**
     * Constructs a new <code>TopupCredit201Response</code>.
     * @alias module:model/TopupCredit201Response
     */
    constructor() { 
        
        TopupCredit201Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TopupCredit201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TopupCredit201Response} obj Optional instance to populate.
     * @return {module:model/TopupCredit201Response} The populated <code>TopupCredit201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TopupCredit201Response();

            if (data.hasOwnProperty('topup')) {
                obj['topup'] = CreditJournal.constructFromObject(data['topup']);
            }
            if (data.hasOwnProperty('payment')) {
                obj['payment'] = Payment.constructFromObject(data['payment']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TopupCredit201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TopupCredit201Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `topup`
        if (data['topup']) { // data not null
          CreditJournal.validateJSON(data['topup']);
        }
        // validate the optional field `payment`
        if (data['payment']) { // data not null
          Payment.validateJSON(data['payment']);
        }

        return true;
    }


}



/**
 * @member {module:model/CreditJournal} topup
 */
TopupCredit201Response.prototype['topup'] = undefined;

/**
 * @member {module:model/Payment} payment
 */
TopupCredit201Response.prototype['payment'] = undefined;






export default TopupCredit201Response;

