/**
 * BPS
 * Bubble Point System API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LocationTypDevices from './LocationTypDevices';

/**
 * The TypDeviceLocations model module.
 * @module model/TypDeviceLocations
 * @version 0.1.0
 */
class TypDeviceLocations {
    /**
     * Constructs a new <code>TypDeviceLocations</code>.
     * @alias module:model/TypDeviceLocations
     * @param locations {Array.<module:model/LocationTypDevices>} 
     */
    constructor(locations) { 
        
        TypDeviceLocations.initialize(this, locations);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, locations) { 
        obj['locations'] = locations;
    }

    /**
     * Constructs a <code>TypDeviceLocations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TypDeviceLocations} obj Optional instance to populate.
     * @return {module:model/TypDeviceLocations} The populated <code>TypDeviceLocations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TypDeviceLocations();

            if (data.hasOwnProperty('locations')) {
                obj['locations'] = ApiClient.convertToType(data['locations'], [LocationTypDevices]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TypDeviceLocations</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TypDeviceLocations</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TypDeviceLocations.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['locations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['locations'])) {
                throw new Error("Expected the field `locations` to be an array in the JSON data but got " + data['locations']);
            }
            // validate the optional field `locations` (array)
            for (const item of data['locations']) {
                LocationTypDevices.validateJSON(item);
            };
        }

        return true;
    }


}

TypDeviceLocations.RequiredProperties = ["locations"];

/**
 * @member {Array.<module:model/LocationTypDevices>} locations
 */
TypDeviceLocations.prototype['locations'] = undefined;






export default TypDeviceLocations;

