/**
 * BPS
 * Bubble Point System API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Device from './Device';

/**
 * The TypDevices model module.
 * @module model/TypDevices
 * @version 0.1.0
 */
class TypDevices {
    /**
     * Constructs a new <code>TypDevices</code>.
     * @alias module:model/TypDevices
     * @param typ {String} 
     * @param devices {Array.<module:model/Device>} 
     */
    constructor(typ, devices) { 
        
        TypDevices.initialize(this, typ, devices);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, typ, devices) { 
        obj['typ'] = typ;
        obj['devices'] = devices;
    }

    /**
     * Constructs a <code>TypDevices</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TypDevices} obj Optional instance to populate.
     * @return {module:model/TypDevices} The populated <code>TypDevices</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TypDevices();

            if (data.hasOwnProperty('typ')) {
                obj['typ'] = ApiClient.convertToType(data['typ'], 'String');
            }
            if (data.hasOwnProperty('devices')) {
                obj['devices'] = ApiClient.convertToType(data['devices'], [Device]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TypDevices</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TypDevices</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TypDevices.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['typ'] && !(typeof data['typ'] === 'string' || data['typ'] instanceof String)) {
            throw new Error("Expected the field `typ` to be a primitive type in the JSON string but got " + data['typ']);
        }
        if (data['devices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['devices'])) {
                throw new Error("Expected the field `devices` to be an array in the JSON data but got " + data['devices']);
            }
            // validate the optional field `devices` (array)
            for (const item of data['devices']) {
                Device.validateJSON(item);
            };
        }

        return true;
    }


}

TypDevices.RequiredProperties = ["typ", "devices"];

/**
 * @member {String} typ
 */
TypDevices.prototype['typ'] = undefined;

/**
 * @member {Array.<module:model/Device>} devices
 */
TypDevices.prototype['devices'] = undefined;






export default TypDevices;

