/**
 * BPS
 * Bubble Point System API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateModuleProgrammStatusRequest model module.
 * @module model/UpdateModuleProgrammStatusRequest
 * @version 0.1.0
 */
class UpdateModuleProgrammStatusRequest {
    /**
     * Constructs a new <code>UpdateModuleProgrammStatusRequest</code>.
     * @alias module:model/UpdateModuleProgrammStatusRequest
     * @param checksum {String} 
     * @param status {String} 
     */
    constructor(checksum, status) { 
        
        UpdateModuleProgrammStatusRequest.initialize(this, checksum, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, checksum, status) { 
        obj['checksum'] = checksum;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>UpdateModuleProgrammStatusRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateModuleProgrammStatusRequest} obj Optional instance to populate.
     * @return {module:model/UpdateModuleProgrammStatusRequest} The populated <code>UpdateModuleProgrammStatusRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateModuleProgrammStatusRequest();

            if (data.hasOwnProperty('checksum')) {
                obj['checksum'] = ApiClient.convertToType(data['checksum'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateModuleProgrammStatusRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateModuleProgrammStatusRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateModuleProgrammStatusRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['checksum'] && !(typeof data['checksum'] === 'string' || data['checksum'] instanceof String)) {
            throw new Error("Expected the field `checksum` to be a primitive type in the JSON string but got " + data['checksum']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

UpdateModuleProgrammStatusRequest.RequiredProperties = ["checksum", "status"];

/**
 * @member {String} checksum
 */
UpdateModuleProgrammStatusRequest.prototype['checksum'] = undefined;

/**
 * @member {String} status
 */
UpdateModuleProgrammStatusRequest.prototype['status'] = undefined;






export default UpdateModuleProgrammStatusRequest;

