/*
 * BPS
 * Bubble Point System API
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Module from './Module';
import Pump from './Pump';
import WasherStatus from './WasherStatus';

/**
 * The Washer model module.
 * @module model/Washer
 * @version 0.1.0
 */
export default class Washer {
  /**
   * Constructs a new <code>Washer</code>.
   * @alias module:model/Washer
   * @class
   * @param id {String} 
   * @param location {String} 
   * @param priceLine {String} 
   * @param module {module:model/Module} 
   * @param detergent {module:model/Pump} 
   * @param softener {module:model/Pump} 
   * @param status {module:model/WasherStatus} 
   */
  constructor(id, location, priceLine, module, detergent, softener, status) {
    this.id = id;
    this.location = location;
    this.priceLine = priceLine;
    this.module = module;
    this.detergent = detergent;
    this.softener = softener;
    this.status = status;
  }

  /**
   * Constructs a <code>Washer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Washer} obj Optional instance to populate.
   * @return {module:model/Washer} The populated <code>Washer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Washer();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('price_line'))
        obj.priceLine = ApiClient.convertToType(data['price_line'], 'String');
      if (data.hasOwnProperty('module'))
        obj.module = Module.constructFromObject(data['module']);
      if (data.hasOwnProperty('detergent'))
        obj.detergent = Pump.constructFromObject(data['detergent']);
      if (data.hasOwnProperty('softener'))
        obj.softener = Pump.constructFromObject(data['softener']);
      if (data.hasOwnProperty('status'))
        obj.status = WasherStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Washer.prototype.id = undefined;

/**
 * @member {String} location
 */
Washer.prototype.location = undefined;

/**
 * @member {String} priceLine
 */
Washer.prototype.priceLine = undefined;

/**
 * @member {module:model/Module} module
 */
Washer.prototype.module = undefined;

/**
 * @member {module:model/Pump} detergent
 */
Washer.prototype.detergent = undefined;

/**
 * @member {module:model/Pump} softener
 */
Washer.prototype.softener = undefined;

/**
 * @member {module:model/WasherStatus} status
 */
Washer.prototype.status = undefined;

